# Generated by Django 4.1.7 on 2023-03-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Youtubers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('subscribers', models.IntegerField()),
                ('link', models.URLField()),
                ('image', models.FilePathField(path='/img')),
            ],
        ),
    ]
