# Generated by Django 4.1.7 on 2023-03-29 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Youtubers',
            new_name='Youtuber',
        ),
    ]
