# Generated by Django 4.1.7 on 2023-03-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0002_rename_youtubers_youtuber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='image',
            field=models.ImageField(blank=True, default='placeholder.png', upload_to=''),
        ),
    ]
